"""
Learning Curriculum — Predefined topic and module definitions.

This is the source of truth for the Learning Engine.
The LLM generates lesson CONTENT for each module, but the curriculum
(topic list, module order, titles, objectives) is hardcoded here.

Adding a new topic: add an entry to LEARNING_CURRICULUM.
Adding a module: append to the topic's "modules" list.
"""

LEARNING_CURRICULUM = [
    {
        "name": "Azure",
        "slug": "azure-track",
        "description": "Master Microsoft Azure from fundamentals to advanced architecture.",
        "icon": "☁️",
        "difficulty_range": "Beginner → Advanced",
        "estimated_hours": 40,
        "modules": [
            {"seq": 1,  "title": "Azure Fundamentals",          "difficulty": "beginner",     "duration": 30, "objectives": ["Understand cloud concepts", "Describe Azure architecture"], "keywords": ["cloud computing", "azure fundamentals", "AZ-900"]},
            {"seq": 2,  "title": "Azure Regions and Zones",     "difficulty": "beginner",     "duration": 25, "objectives": ["Explain Azure regions", "Understand availability zones"], "keywords": ["azure regions", "availability zones", "geography"]},
            {"seq": 3,  "title": "Resource Groups",             "difficulty": "beginner",     "duration": 20, "objectives": ["Create resource groups", "Manage Azure resources"], "keywords": ["resource groups", "azure management", "subscriptions"]},
            {"seq": 4,  "title": "Azure Storage Fundamentals",  "difficulty": "beginner",     "duration": 35, "objectives": ["Describe storage types", "Choose correct storage tier"], "keywords": ["azure storage", "blob storage", "file storage"]},
            {"seq": 5,  "title": "Azure Blob Storage",          "difficulty": "beginner",     "duration": 35, "objectives": ["Create blob containers", "Upload and manage blobs"], "keywords": ["blob storage", "containers", "data lake"]},
            {"seq": 6,  "title": "Azure Virtual Machines",      "difficulty": "intermediate", "duration": 40, "objectives": ["Deploy VMs", "Configure VM networking"], "keywords": ["virtual machines", "IaaS", "compute"]},
            {"seq": 7,  "title": "Azure Virtual Networks",      "difficulty": "intermediate", "duration": 40, "objectives": ["Design VNets", "Configure subnets and NSGs"], "keywords": ["VNet", "subnets", "NSG", "networking"]},
            {"seq": 8,  "title": "Azure App Service",           "difficulty": "intermediate", "duration": 35, "objectives": ["Deploy web apps", "Configure App Service plans"], "keywords": ["app service", "PaaS", "web apps"]},
            {"seq": 9,  "title": "Azure Functions",             "difficulty": "intermediate", "duration": 30, "objectives": ["Build serverless functions", "Use triggers and bindings"], "keywords": ["azure functions", "serverless", "event-driven"]},
            {"seq": 10, "title": "Azure SQL Database",          "difficulty": "intermediate", "duration": 35, "objectives": ["Create SQL databases", "Configure backups and security"], "keywords": ["azure sql", "managed database", "PaaS"]},
            {"seq": 11, "title": "Azure Identity & Entra ID",   "difficulty": "intermediate", "duration": 40, "objectives": ["Manage identities", "Configure RBAC"], "keywords": ["entra id", "azure AD", "RBAC", "identity"]},
            {"seq": 12, "title": "Azure Security Center",       "difficulty": "intermediate", "duration": 35, "objectives": ["Monitor security posture", "Respond to threats"], "keywords": ["security center", "defender for cloud", "security score"]},
            {"seq": 13, "title": "Azure Key Vault",             "difficulty": "intermediate", "duration": 30, "objectives": ["Store secrets securely", "Manage certificates and keys"], "keywords": ["key vault", "secrets management", "encryption"]},
            {"seq": 14, "title": "Azure Monitor",               "difficulty": "intermediate", "duration": 35, "objectives": ["Set up monitoring", "Create alerts and dashboards"], "keywords": ["azure monitor", "log analytics", "application insights"]},
            {"seq": 15, "title": "Azure Kubernetes Service",    "difficulty": "advanced",     "duration": 50, "objectives": ["Deploy AKS clusters", "Manage containerized workloads"], "keywords": ["AKS", "kubernetes", "containers", "pods"]},
            {"seq": 16, "title": "Azure DevOps Pipelines",      "difficulty": "advanced",     "duration": 45, "objectives": ["Build CI/CD pipelines", "Automate deployments"], "keywords": ["azure devops", "CI/CD", "pipelines", "YAML"]},
            {"seq": 17, "title": "Azure Architecture Patterns", "difficulty": "advanced",     "duration": 45, "objectives": ["Apply Well-Architected Framework", "Design resilient systems"], "keywords": ["well-architected", "reliability", "cloud design"]},
            {"seq": 18, "title": "Azure Cost Management",       "difficulty": "advanced",     "duration": 30, "objectives": ["Optimize Azure spend", "Set budgets and alerts"], "keywords": ["cost management", "azure pricing", "optimization"]},
        ],
    },
    {
        "name": "Microsoft Fabric",
        "slug": "fabric-track",
        "description": "Complete Microsoft Fabric analytics platform from OneLake to Real-Time Intelligence.",
        "icon": "🗄️",
        "difficulty_range": "Beginner → Advanced",
        "estimated_hours": 30,
        "modules": [
            {"seq": 1,  "title": "Fabric Fundamentals",         "difficulty": "beginner",     "duration": 30, "objectives": ["Understand Fabric architecture", "Navigate the Fabric portal"], "keywords": ["microsoft fabric", "unified analytics", "SaaS"]},
            {"seq": 2,  "title": "OneLake Architecture",        "difficulty": "beginner",     "duration": 30, "objectives": ["Understand OneLake", "Manage data in OneLake"], "keywords": ["OneLake", "data lake", "storage"]},
            {"seq": 3,  "title": "Fabric Data Factory",         "difficulty": "beginner",     "duration": 35, "objectives": ["Build data pipelines", "Use dataflows"], "keywords": ["data factory", "pipelines", "ETL", "data integration"]},
            {"seq": 4,  "title": "Lakehouse in Fabric",         "difficulty": "intermediate", "duration": 40, "objectives": ["Create lakehouses", "Work with Delta tables"], "keywords": ["lakehouse", "delta lake", "medallion architecture"]},
            {"seq": 5,  "title": "Warehouse in Fabric",         "difficulty": "intermediate", "duration": 40, "objectives": ["Build Fabric warehouses", "Write T-SQL queries"], "keywords": ["synapse data warehouse", "T-SQL", "data warehouse"]},
            {"seq": 6,  "title": "Spark Notebooks",             "difficulty": "intermediate", "duration": 45, "objectives": ["Write PySpark code", "Process large datasets"], "keywords": ["spark", "pyspark", "notebooks", "data engineering"]},
            {"seq": 7,  "title": "Real-Time Intelligence",      "difficulty": "intermediate", "duration": 40, "objectives": ["Use KQL databases", "Stream with Eventstream"], "keywords": ["KQL", "eventstream", "real-time analytics"]},
            {"seq": 8,  "title": "Power BI in Fabric",          "difficulty": "intermediate", "duration": 35, "objectives": ["Create semantic models", "Build interactive reports"], "keywords": ["power bi", "semantic model", "direct lake", "reports"]},
            {"seq": 9,  "title": "Data Science in Fabric",      "difficulty": "advanced",     "duration": 50, "objectives": ["Run ML experiments", "Use MLflow tracking"], "keywords": ["data science", "machine learning", "MLflow", "experiments"]},
            {"seq": 10, "title": "Fabric Administration",       "difficulty": "advanced",     "duration": 35, "objectives": ["Manage workspaces", "Configure security and governance"], "keywords": ["fabric admin", "governance", "workspace management"]},
        ],
    },
    {
        "name": "Power BI",
        "slug": "powerbi-track",
        "description": "Build compelling data visualisations and BI solutions with Power BI.",
        "icon": "📊",
        "difficulty_range": "Beginner → Advanced",
        "estimated_hours": 25,
        "modules": [
            {"seq": 1,  "title": "Power BI Desktop Basics",     "difficulty": "beginner",     "duration": 30, "objectives": ["Navigate Power BI Desktop", "Connect to data sources"], "keywords": ["power bi desktop", "data connection", "reports"]},
            {"seq": 2,  "title": "Data Transformation (Power Query)", "difficulty": "beginner", "duration": 35, "objectives": ["Clean and transform data", "Write M formulas"], "keywords": ["power query", "M language", "data transformation"]},
            {"seq": 3,  "title": "Data Modelling",              "difficulty": "beginner",     "duration": 40, "objectives": ["Create star schemas", "Define relationships"], "keywords": ["data model", "star schema", "relationships", "cardinality"]},
            {"seq": 4,  "title": "DAX Fundamentals",            "difficulty": "intermediate", "duration": 45, "objectives": ["Write calculated columns", "Create measures"], "keywords": ["DAX", "measures", "calculated columns", "filter context"]},
            {"seq": 5,  "title": "Advanced DAX",                "difficulty": "intermediate", "duration": 50, "objectives": ["Use time intelligence", "Master CALCULATE"], "keywords": ["DAX", "CALCULATE", "time intelligence", "ALLSELECTED"]},
            {"seq": 6,  "title": "Visualisations and Reports",  "difficulty": "intermediate", "duration": 35, "objectives": ["Choose right visuals", "Apply design best practices"], "keywords": ["visuals", "charts", "report design", "UX"]},
            {"seq": 7,  "title": "Power BI Service",            "difficulty": "intermediate", "duration": 30, "objectives": ["Publish to cloud", "Configure scheduled refresh"], "keywords": ["power bi service", "workspaces", "publish", "refresh"]},
            {"seq": 8,  "title": "Row-Level Security",          "difficulty": "advanced",     "duration": 35, "objectives": ["Implement RLS", "Test security roles"], "keywords": ["RLS", "security", "data access", "roles"]},
            {"seq": 9,  "title": "Power BI Deployment Pipelines", "difficulty": "advanced",  "duration": 30, "objectives": ["Manage dev/test/prod", "Deploy with confidence"], "keywords": ["deployment pipelines", "ALM", "CI/CD", "power bi"]},
            {"seq": 10, "title": "Power BI Embedded Analytics", "difficulty": "advanced",    "duration": 40, "objectives": ["Embed reports in apps", "Use Embed tokens"], "keywords": ["power bi embedded", "ISV", "REST API", "embed token"]},
        ],
    },
    {
        "name": "Azure AI",
        "slug": "azure-ai-track",
        "description": "Build intelligent AI applications on Azure using OpenAI, Cognitive Services, and AI Studio.",
        "icon": "🧠",
        "difficulty_range": "Beginner → Advanced",
        "estimated_hours": 30,
        "modules": [
            {"seq": 1,  "title": "AI Fundamentals",             "difficulty": "beginner",     "duration": 25, "objectives": ["Understand AI concepts", "Identify Azure AI services"], "keywords": ["AI fundamentals", "machine learning", "AI-900"]},
            {"seq": 2,  "title": "Azure Cognitive Services",    "difficulty": "beginner",     "duration": 35, "objectives": ["Use vision APIs", "Use language APIs"], "keywords": ["cognitive services", "computer vision", "text analytics"]},
            {"seq": 3,  "title": "Azure OpenAI Service",        "difficulty": "intermediate", "duration": 40, "objectives": ["Deploy GPT models", "Call the Completions API"], "keywords": ["azure openai", "GPT", "ChatGPT", "embeddings"]},
            {"seq": 4,  "title": "Prompt Engineering",          "difficulty": "intermediate", "duration": 35, "objectives": ["Write effective prompts", "Use few-shot techniques"], "keywords": ["prompt engineering", "system prompt", "few-shot", "chain of thought"]},
            {"seq": 5,  "title": "RAG (Retrieval Augmented Generation)", "difficulty": "intermediate", "duration": 45, "objectives": ["Build RAG pipelines", "Use Azure AI Search"], "keywords": ["RAG", "vector search", "embeddings", "AI search"]},
            {"seq": 6,  "title": "Azure AI Foundry",            "difficulty": "intermediate", "duration": 40, "objectives": ["Use AI Foundry portal", "Evaluate models"], "keywords": ["AI foundry", "AI studio", "model evaluation", "deployments"]},
            {"seq": 7,  "title": "Responsible AI",              "difficulty": "intermediate", "duration": 30, "objectives": ["Apply fairness principles", "Use content filters"], "keywords": ["responsible AI", "fairness", "content safety", "explainability"]},
            {"seq": 8,  "title": "Fine-tuning Models",          "difficulty": "advanced",     "duration": 50, "objectives": ["Fine-tune GPT models", "Evaluate fine-tuned models"], "keywords": ["fine-tuning", "RLHF", "custom models", "training data"]},
            {"seq": 9,  "title": "Multi-modal AI",              "difficulty": "advanced",     "duration": 45, "objectives": ["Work with DALL-E", "Process images with GPT-4V"], "keywords": ["multimodal", "DALL-E", "image generation", "vision models"]},
            {"seq": 10, "title": "AI Agents and Copilot Studio","difficulty": "advanced",     "duration": 45, "objectives": ["Build AI agents", "Orchestrate with Semantic Kernel"], "keywords": ["AI agents", "semantic kernel", "copilot studio", "orchestration"]},
        ],
    },
    {
        "name": "Azure Data Engineering",
        "slug": "data-engineering-track",
        "description": "Design and build production-grade data pipelines on Azure.",
        "icon": "🔧",
        "difficulty_range": "Beginner → Advanced",
        "estimated_hours": 35,
        "modules": [
            {"seq": 1,  "title": "Data Engineering Fundamentals","difficulty": "beginner",    "duration": 25, "objectives": ["Understand data engineering roles", "Map Azure data services"], "keywords": ["data engineering", "DP-203", "azure data"]},
            {"seq": 2,  "title": "Azure Data Factory Basics",   "difficulty": "beginner",     "duration": 40, "objectives": ["Create pipelines", "Use linked services"], "keywords": ["azure data factory", "ADF", "pipelines", "ETL"]},
            {"seq": 3,  "title": "Azure Data Lake Storage Gen2","difficulty": "beginner",     "duration": 35, "objectives": ["Set up ADLS Gen2", "Manage hierarchical namespaces"], "keywords": ["ADLS Gen2", "data lake", "storage", "hierarchical namespace"]},
            {"seq": 4,  "title": "Azure Synapse Analytics",     "difficulty": "intermediate", "duration": 45, "objectives": ["Use Synapse workspace", "Run SQL pool queries"], "keywords": ["synapse analytics", "SQL pool", "Spark pool", "integration"]},
            {"seq": 5,  "title": "Azure Databricks",            "difficulty": "intermediate", "duration": 50, "objectives": ["Build Databricks clusters", "Write PySpark ETL jobs"], "keywords": ["databricks", "apache spark", "delta lake", "unity catalog"]},
            {"seq": 6,  "title": "Delta Lake and Lakehouse",    "difficulty": "intermediate", "duration": 40, "objectives": ["Use Delta format", "Implement medallion layers"], "keywords": ["delta lake", "ACID transactions", "medallion architecture", "lakehouse"]},
            {"seq": 7,  "title": "Azure Event Hubs & Streaming","difficulty": "intermediate", "duration": 40, "objectives": ["Ingest streaming data", "Process with Spark Streaming"], "keywords": ["event hubs", "kafka", "streaming", "real-time ingestion"]},
            {"seq": 8,  "title": "Azure Stream Analytics",      "difficulty": "intermediate", "duration": 35, "objectives": ["Write Stream Analytics queries", "Handle windowing"], "keywords": ["stream analytics", "SAQL", "windowing", "IoT"]},
            {"seq": 9,  "title": "Data Quality and Testing",    "difficulty": "advanced",     "duration": 35, "objectives": ["Validate data pipelines", "Implement data quality checks"], "keywords": ["data quality", "great expectations", "testing", "data contracts"]},
            {"seq": 10, "title": "Data Governance with Purview","difficulty": "advanced",     "duration": 35, "objectives": ["Catalog data assets", "Apply data classification"], "keywords": ["microsoft purview", "data catalog", "governance", "lineage"]},
            {"seq": 11, "title": "Pipeline Orchestration",      "difficulty": "advanced",     "duration": 45, "objectives": ["Build complex workflows", "Handle failures and retries"], "keywords": ["orchestration", "ADF triggers", "monitoring", "dependency chains"]},
        ],
    },
    {
        "name": "SQL",
        "slug": "sql-track",
        "description": "Master SQL from basics to advanced query optimisation and database design.",
        "icon": "🗃️",
        "difficulty_range": "Beginner → Advanced",
        "estimated_hours": 20,
        "modules": [
            {"seq": 1,  "title": "SQL Fundamentals",            "difficulty": "beginner",     "duration": 30, "objectives": ["Write SELECT statements", "Filter with WHERE"], "keywords": ["SQL", "SELECT", "WHERE", "relational databases"]},
            {"seq": 2,  "title": "Filtering and Sorting",       "difficulty": "beginner",     "duration": 25, "objectives": ["Use ORDER BY and LIMIT", "Filter with complex conditions"], "keywords": ["ORDER BY", "LIMIT", "AND OR NOT", "SQL filtering"]},
            {"seq": 3,  "title": "Joins",                       "difficulty": "beginner",     "duration": 35, "objectives": ["Write INNER JOINs", "Use LEFT and RIGHT JOINs"], "keywords": ["SQL JOIN", "INNER JOIN", "LEFT JOIN", "table relationships"]},
            {"seq": 4,  "title": "Aggregations and GROUP BY",   "difficulty": "intermediate", "duration": 30, "objectives": ["Use COUNT SUM AVG", "Group and filter with HAVING"], "keywords": ["GROUP BY", "COUNT", "SUM", "HAVING", "aggregation"]},
            {"seq": 5,  "title": "Subqueries and CTEs",         "difficulty": "intermediate", "duration": 35, "objectives": ["Write correlated subqueries", "Use CTEs for readability"], "keywords": ["CTE", "WITH clause", "subquery", "common table expression"]},
            {"seq": 6,  "title": "Window Functions",            "difficulty": "intermediate", "duration": 40, "objectives": ["Use RANK and ROW_NUMBER", "Calculate running totals"], "keywords": ["window functions", "OVER", "PARTITION BY", "RANK", "LAG LEAD"]},
            {"seq": 7,  "title": "Database Design",             "difficulty": "intermediate", "duration": 35, "objectives": ["Design normalised schemas", "Choose primary and foreign keys"], "keywords": ["database design", "normalisation", "ERD", "primary key"]},
            {"seq": 8,  "title": "Indexes and Performance",     "difficulty": "advanced",     "duration": 40, "objectives": ["Create effective indexes", "Read execution plans"], "keywords": ["indexes", "query optimisation", "execution plan", "performance"]},
            {"seq": 9,  "title": "Stored Procedures and Functions","difficulty":"advanced",   "duration": 35, "objectives": ["Write stored procedures", "Create user-defined functions"], "keywords": ["stored procedures", "UDF", "T-SQL", "PL/SQL"]},
            {"seq": 10, "title": "Transactions and Concurrency","difficulty": "advanced",     "duration": 35, "objectives": ["Use ACID transactions", "Handle deadlocks"], "keywords": ["transactions", "ACID", "isolation levels", "concurrency", "deadlock"]},
        ],
    },
    {
        "name": "Databricks",
        "slug": "databricks-track",
        "description": "Master the Databricks Lakehouse Platform for data engineering and ML.",
        "icon": "⚡",
        "difficulty_range": "Beginner → Advanced",
        "estimated_hours": 28,
        "modules": [
            {"seq": 1,  "title": "Databricks Fundamentals",     "difficulty": "beginner",     "duration": 30, "objectives": ["Navigate Databricks workspace", "Understand cluster types"], "keywords": ["databricks", "lakehouse", "workspace", "clusters"]},
            {"seq": 2,  "title": "Apache Spark Basics",         "difficulty": "beginner",     "duration": 40, "objectives": ["Understand Spark architecture", "Use DataFrames"], "keywords": ["apache spark", "RDD", "DataFrame", "lazy evaluation"]},
            {"seq": 3,  "title": "PySpark for Data Engineering","difficulty": "intermediate", "duration": 45, "objectives": ["Transform data with PySpark", "Handle schema evolution"], "keywords": ["pyspark", "data engineering", "transformations", "schema"]},
            {"seq": 4,  "title": "Delta Lake Deep Dive",        "difficulty": "intermediate", "duration": 40, "objectives": ["Use ACID transactions", "Time travel with Delta"], "keywords": ["delta lake", "MERGE", "time travel", "ACID", "delta format"]},
            {"seq": 5,  "title": "Databricks Unity Catalog",    "difficulty": "intermediate", "duration": 35, "objectives": ["Govern data assets", "Manage permissions"], "keywords": ["unity catalog", "data governance", "metastore", "permissions"]},
            {"seq": 6,  "title": "Medallion Architecture",      "difficulty": "intermediate", "duration": 35, "objectives": ["Implement Bronze/Silver/Gold", "Design data quality layers"], "keywords": ["medallion", "bronze silver gold", "lakehouse design", "data quality"]},
            {"seq": 7,  "title": "Databricks ML and MLflow",    "difficulty": "advanced",     "duration": 50, "objectives": ["Track ML experiments", "Register models in MLflow"], "keywords": ["MLflow", "experiment tracking", "model registry", "machine learning"]},
            {"seq": 8,  "title": "Databricks Workflows",        "difficulty": "advanced",     "duration": 35, "objectives": ["Build multi-task workflows", "Monitor job runs"], "keywords": ["databricks workflows", "orchestration", "job scheduling", "DLT"]},
            {"seq": 9,  "title": "Performance Optimisation",    "difficulty": "advanced",     "duration": 40, "objectives": ["Tune Spark jobs", "Use adaptive query execution"], "keywords": ["spark tuning", "AQE", "caching", "partitioning", "Z-ordering"]},
        ],
    },
]
